"""Original, child-friendly Catholic books for the Sanctus Library.

All text here is newly authored for Sanctus (public-domain stories retold in
simple words), so it is free of copyright concerns. Each book has full,
chapter-by-chapter content and is marked with tradition "children" so the
Library groups it into a dedicated "For Children" section (free to read).
"""

CHILDREN_BOOKS = [
    {
        "slug": "bible-stories-for-little-souls",
        "title": "Bible Stories for Little Souls",
        "author": "Sanctus",
        "year": None,
        "blurb": "The greatest true stories ever told, retold gently for little hearts — from the making of the world to the empty tomb of Easter morning.",
        "tradition": "children",
        "cover_color": "#3E6B8A",
        "cover_icon": "book-outline",
        "type": "embedded",
        "chapters": [
            {"title": "1. In the Beginning", "body_md": "In the very beginning, there was only God. God was so full of love that He wanted to share it, so He made the whole world.\n\nHe said, *\"Let there be light,\"* and light came shining out. He made the sky and the seas, the tall mountains and the green trees. He made the sun to warm the day and the moon and stars to sparkle at night.\n\nThen God made the birds to sing and the fish to swim and every animal that runs and hops and crawls. Last of all, God made people — a man and a woman — and He loved them most of all, because they could love Him back.\n\nGod looked at everything He had made and said, *\"It is very good.\"* And on the seventh day He rested.\n\n**Little prayer:** *Thank You, God, for making the world, and for making me.*"},
            {"title": "2. Noah and the Great Ark", "body_md": "After many years, most people forgot about God and were unkind to one another. But one man named Noah still loved God with all his heart.\n\nGod asked Noah to build a giant boat called an ark. *\"A great flood is coming,\"* God said. *\"Bring your family, and two of every animal, so they will be safe.\"*\n\nNoah obeyed. Two by two the animals came — lions and lambs, elephants and mice, doves and donkeys. Then the rain fell for forty days and forty nights, but everyone inside the ark was safe.\n\nAt last the rain stopped. Noah sent out a dove, and it came back with a green leaf — dry land was near! God placed a beautiful rainbow in the sky as a promise: *\"I will always take care of you.\"*\n\n**Little prayer:** *Thank You, God, for keeping me safe like You kept Noah.*"},
            {"title": "3. God Calls Abraham", "body_md": "There was a good man named Abraham. One day God spoke to him: *\"Leave your home and go to a new land that I will show you. I will make your family as many as the stars in the sky.\"*\n\nAbraham trusted God, even though he did not know the way. He packed up everything and set out with his wife Sarah.\n\nAt night Abraham looked up at the sky. There were more stars than he could ever count! God had promised that his family would be that big someday — and God always keeps His promises.\n\nAbraham became the father of God's special family, and from that family, long after, Jesus would be born.\n\n**Little prayer:** *Help me to trust You, God, even when I cannot see the whole way.*"},
            {"title": "4. Moses and the Sea that Opened", "body_md": "God's people, the Israelites, were kept as slaves in the land of Egypt. They cried out to God for help, and God chose a man named Moses to lead them to freedom.\n\nMoses said to the king, *\"Let God's people go!\"* At last the king let them leave. But then he changed his mind and chased them with his soldiers all the way to the edge of the sea.\n\nThe people were afraid — water in front, soldiers behind! But Moses lifted his staff, and God made a path right through the sea. The water stood up like walls on each side, and the people walked across on dry ground.\n\nWhen they were safely across, the waters closed again. God had saved His people.\n\n**Little prayer:** *You are strong, God. Thank You for always making a way.*"},
            {"title": "5. Little David and the Giant", "body_md": "David was the youngest boy in his family. He looked after the sheep and played songs to God on his harp.\n\nOne day a giant soldier named Goliath frightened all of God's people. He was taller than a door and shouted very loud. No one was brave enough to face him — except little David.\n\n*\"I am not afraid,\"* said David, *\"because God is with me.\"* He took only his sling and five small stones from the stream.\n\nDavid swung his sling, and a single stone flew straight and true. Down fell the great giant! God had helped the small, brave boy do a mighty thing.\n\n**Little prayer:** *When I feel small, God, help me remember You are with me.*"},
            {"title": "6. Daniel in the Lions' Den", "body_md": "Daniel loved God so much that he prayed three times every day. Some jealous men made a rule: *\"Anyone who prays to God will be thrown to the lions!\"*\n\nBut Daniel kept praying, because he loved God more than he feared the lions. So he was thrown into a dark den full of hungry lions.\n\nAll night the king could not sleep. In the morning he ran to the den and called out. *\"Daniel, are you there?\"*\n\n*\"I am!\"* said Daniel. *\"God sent an angel to close the lions' mouths. They did not hurt me at all.\"*\n\nThe king was amazed, and he told everyone to honour Daniel's God.\n\n**Little prayer:** *Help me pray to You every day, God, like Daniel did.*"},
            {"title": "7. The Angel Visits Mary", "body_md": "In a little town called Nazareth lived a young girl named Mary. She loved God very much and always tried to do His will.\n\nOne day the angel Gabriel came to her, shining bright. *\"Do not be afraid, Mary,\"* he said. *\"God has chosen you. You will have a baby boy, and you will name Him Jesus. He will be the Son of God.\"*\n\nMary was surprised, but she trusted God. She said the most beautiful words: *\"Let it be done to me as you say.\"*\n\nBecause Mary said yes, Jesus would come into the world to save us. That is why we call her our Blessed Mother.\n\n**Little prayer:** *Mary, help me say \"yes\" to God like you did.*"},
            {"title": "8. The Night Jesus Was Born", "body_md": "Mary and her husband Joseph travelled to the town of Bethlehem. But the town was so full that there was no room anywhere to stay. At last they found a little stable where the animals slept.\n\nThat night, in the quiet stable, baby Jesus was born. Mary wrapped Him warmly and laid Him in a manger — the box where the animals ate their hay.\n\nOut in the fields, shepherds were watching their sheep. Suddenly angels filled the sky and sang, *\"Glory to God! A Saviour is born!\"* The shepherds hurried to find the baby and knelt down to worship Him.\n\nFar away, wise men followed a bright new star to bring gifts to the newborn King.\n\n**Little prayer:** *Happy birthday, Jesus. Thank You for coming to us.*"},
            {"title": "9. Jesus Calms the Storm", "body_md": "One evening Jesus and His friends got into a boat to cross the lake. Jesus was so tired that He fell fast asleep.\n\nSuddenly a great storm blew up. The wind howled and the waves crashed over the sides of the boat. The friends were terrified. *\"Jesus, wake up! We are going to sink!\"*\n\nJesus stood up and looked at the roaring wind and waves. *\"Peace,\"* He said. *\"Be still.\"* At once the storm stopped, and the lake was calm and smooth as glass.\n\nHis friends were amazed. *\"Even the wind and the sea obey Him!\"* they whispered. They learned that Jesus is stronger than any storm.\n\n**Little prayer:** *Jesus, when I am scared, help me remember that You are near.*"},
            {"title": "10. The Good Shepherd", "body_md": "Jesus loved to tell stories to help people understand God. One day He said, *\"I am the Good Shepherd.\"*\n\nA good shepherd knows every one of his sheep by name. He leads them to green grass and cool water. And if even one little sheep gets lost, he leaves the ninety-nine others and searches everywhere until he finds it.\n\nWhen he finds the lost sheep, he lifts it gently onto his shoulders and carries it home, full of joy. *\"Rejoice with me,\"* he says, *\"for I have found my sheep!\"*\n\nJesus is our Good Shepherd. He knows your name, and He will always come looking for you.\n\n**Little prayer:** *Thank You, Jesus, for being my Good Shepherd.*"},
            {"title": "11. Jesus Feeds the Crowd", "body_md": "A huge crowd of people once followed Jesus all day to hear Him teach. When evening came, they were hungry and there was no food to buy.\n\nA little boy had brought five small loaves of bread and two fish. He gave them all to Jesus. It did not seem like much for so many people!\n\nJesus took the bread and the fish, looked up to heaven, and thanked God. Then He broke the bread and gave it out — and it kept coming and coming! Everyone ate until they were full, and there were even twelve baskets left over.\n\nThe little boy learned that when we give what we have to Jesus, He can do wonderful things.\n\n**Little prayer:** *Jesus, I give You what I have. Please make it enough.*"},
            {"title": "12. The Cross and the Empty Tomb", "body_md": "Because Jesus loves us so much, He was willing to suffer for us. On a hill, He was nailed to a cross and died to take away our sins. His friends were very sad, and they laid Him gently in a tomb cut from the rock.\n\nBut that was not the end of the story!\n\nEarly on Sunday morning, some women came to the tomb — and the great stone was rolled away. An angel shone there and said, *\"Do not be afraid. Jesus is not here. He is risen, just as He said!\"*\n\nJesus was alive again! He had beaten death forever. This is the happiest news in all the world, and we celebrate it every Easter.\n\n**Little prayer:** *Jesus, You are alive! Thank You for loving me that much.*"},
        ],
    },
    {
        "slug": "little-saints-for-little-hearts",
        "title": "Little Saints for Little Hearts",
        "author": "Sanctus",
        "year": None,
        "blurb": "Meet the friends of God — brave, kind and joyful saints whose true stories show little ones how to love Jesus every day.",
        "tradition": "children",
        "cover_color": "#8A6A2E",
        "cover_icon": "sparkles-outline",
        "type": "embedded",
        "chapters": [
            {"title": "1. Your Guardian Angel", "body_md": "Did you know that God has given you a special friend who is always by your side? It is your Guardian Angel.\n\nAngels are spirits made by God. They cannot be seen with our eyes, but they are very real. Your angel watches over you all day and all night, keeping you close to God and helping you choose what is good.\n\nWhen you wake up, you can say hello to your angel. When you go to sleep, your angel keeps watch. You are never, ever alone.\n\n**A prayer to your angel:**\n\n*Angel of God, my guardian dear,*\n*to whom God's love commits me here,*\n*ever this day be at my side,*\n*to light and guard, to rule and guide. Amen.*"},
            {"title": "2. St. Joseph, the Quiet Helper", "body_md": "St. Joseph was the husband of Mary and the earthly father of Jesus. He was a carpenter, which means he made things out of wood.\n\nJoseph did not say many words in the Bible, but he did many good deeds. He kept Mary and Jesus safe. When danger came, God warned him in a dream, and Joseph got up right away to protect his family.\n\nHe taught Jesus how to work with his hands and how to pray. He worked hard every day to give his family a home.\n\nSt. Joseph shows us that quiet, faithful helpers are very special to God.\n\n**Little prayer:** *St. Joseph, help me to be a quiet, faithful helper too.*"},
            {"title": "3. St. Francis and the Animals", "body_md": "St. Francis lived in Italy long ago. When he was young he liked fine clothes and parties, but then he fell in love with Jesus and gave everything he had to the poor.\n\nFrancis saw God in everything — in the sun, the moon, the flowers and the streams. He called them Brother Sun and Sister Moon.\n\nHe loved animals dearly. The birds would gather around him to listen as he preached, and it is said he even made peace with a fierce wolf. Every creature seemed to know he was their friend.\n\nSt. Francis teaches us to care for God's creation and to live simply, with a joyful heart.\n\n**Little prayer:** *Lord, make me a friend to all You have made.*"},
            {"title": "4. St. Thérèse and the Little Way", "body_md": "St. Thérèse was a young nun in France. She wanted to do great things for God, but she was small and could not travel the world or do mighty deeds.\n\nSo she found her own path, which she called *the Little Way*. She did small, ordinary things — like a chore, a kind word, or a smile — but she did them all with great love for Jesus.\n\nShe said that little acts of love are like petals we scatter for God. Even the tiniest child can walk her Little Way.\n\nSt. Thérèse promised to spend her heaven doing good on earth, sending down a shower of roses.\n\n**Little prayer:** *Jesus, help me do little things with great love.*"},
            {"title": "5. St. Nicholas, the Secret Giver", "body_md": "Long ago there lived a kind bishop named Nicholas. He loved Jesus and he loved to give — but he liked to give in secret, so that only God would see.\n\nThere was a poor family who had no money at all. One night, Nicholas quietly dropped bags of gold coins through their window. Some say the coins landed in stockings drying by the fire!\n\nHe helped many people this way, never wanting a thank-you. That is why, at Christmas, we still give secret gifts and remember good St. Nicholas.\n\nHe shows us the joy of giving without needing to be seen.\n\n**Little prayer:** *St. Nicholas, help me give kindly and quietly, just for God.*"},
            {"title": "6. St. Patrick and the Shamrock", "body_md": "St. Patrick brought the good news of Jesus to the land of Ireland. When he was a boy he had been taken far from home, but he prayed to God every day, and God stayed close to him.\n\nWhen he grew up, Patrick returned to Ireland to teach the people about God. But how could he explain that God is Three Persons — Father, Son and Holy Spirit — yet only one God?\n\nHe bent down and picked a little green shamrock. *\"See,\"* he said, *\"three leaves, but one plant. So it is with the Holy Trinity.\"*\n\nSt. Patrick teaches us to trust God and to share His love with others.\n\n**Little prayer:** *God — Father, Son and Holy Spirit — I love You.*"},
            {"title": "7. St. Bernadette and the Lady", "body_md": "Bernadette was a poor, sickly girl who lived in a town called Lourdes in France. One day, while gathering firewood by a rocky cave, she saw a beautiful Lady dressed in white.\n\nThe Lady was gentle and kind, and she asked Bernadette to pray. She told her to dig in the ground, and there a spring of clean water began to bubble up. Many sick people who came to that water were healed.\n\nThe beautiful Lady was Mary, our Blessed Mother. Bernadette was simple and humble, and Mary chose her to share a message: *pray and trust in God.*\n\n**Little prayer:** *Mother Mary, teach me to pray like little Bernadette.*"},
            {"title": "8. St. Kateri, Lily of the Mohawks", "body_md": "Kateri Tekakwitha was a young Native American girl who lived in North America long ago. She belonged to the Mohawk people.\n\nWhen Kateri heard about Jesus, her heart filled with love, and she was baptized. She loved to pray, especially before the cross, and she was always kind to the sick and the old.\n\nSome people were unkind to her because she followed Jesus, but Kateri stayed faithful and gentle. She is called the *Lily of the Mohawks* because her soul was pure and beautiful like a flower.\n\nSt. Kateri shows us to be brave and true, no matter what others say.\n\n**Little prayer:** *St. Kateri, help me be brave in loving Jesus.*"},
            {"title": "9. St. John Bosco and the Boys", "body_md": "St. John Bosco, whom everyone called Don Bosco, lived in Italy. He loved children, especially poor boys who had no one to care for them.\n\nDon Bosco gathered them together, taught them games, and did fun juggling tricks to make them laugh. But he always ended the day by teaching them about Jesus and how to pray.\n\nHe gave the boys a home, a school, and a trade so they could grow up good and happy. He had a simple secret: be joyful, work hard, and love God.\n\nSt. John Bosco teaches us that being holy can also be full of fun and friendship.\n\n**Little prayer:** *St. John Bosco, help me be joyful and kind to my friends.*"},
        ],
    },
    {
        "slug": "the-holy-mass-for-little-ones",
        "title": "The Holy Mass for Little Ones",
        "author": "Sanctus",
        "year": None,
        "blurb": "A gentle walk through the Mass, step by step, so that little ones can understand and love the greatest prayer of all.",
        "tradition": "children",
        "cover_color": "#8A2E2E",
        "cover_icon": "heart-outline",
        "type": "embedded",
        "chapters": [
            {"title": "1. Why We Go to Mass", "body_md": "Every Sunday, families all around the world go to church for something very special called the Mass.\n\nThe Mass is the greatest prayer there is. It is where we come together as God's family to thank Him, to listen to Him, and to receive Jesus Himself.\n\nSunday is the Lord's Day — the day Jesus rose from the dead. So we make it a happy day and give the very best of our time to God.\n\nWhen you walk into church, you are walking into God's house. That is why we speak softly and behave gently: because Jesus is truly here.\n\n**Little prayer:** *Jesus, I am so happy to come to Your house today.*"},
            {"title": "2. Making the Sign of the Cross", "body_md": "The Mass begins with a prayer we make with our hand and our words: the Sign of the Cross.\n\nWe touch our forehead, then our chest, then our left shoulder, then our right, and we say: *\"In the name of the Father, and of the Son, and of the Holy Spirit. Amen.\"*\n\nThis reminds us of the Holy Trinity — one God in three Persons — and of the cross where Jesus showed His love for us.\n\nTry to make your Sign of the Cross slowly and carefully, not in a rush. It is a little prayer all by itself.\n\n**Little prayer:** *In the name of the Father, and of the Son, and of the Holy Spirit. Amen.*"},
            {"title": "3. We Say Sorry to God", "body_md": "Near the beginning of Mass, we all stop and think about the times we have not been kind or good.\n\nNobody is perfect — we all make mistakes. But God is full of mercy and loves to forgive us when we are truly sorry.\n\nSo together we tell God we are sorry and ask Him to help us do better. We say, *\"Lord, have mercy. Christ, have mercy. Lord, have mercy.\"*\n\nWhen we say sorry with a humble heart, God wipes our hearts clean, like the sun coming out after the rain.\n\n**Little prayer:** *Lord, I am sorry for my sins. Please help me to love better.*"},
            {"title": "4. The Word of God", "body_md": "Now it is time to listen. Someone reads to us from the Bible, God's own book. These are called the readings.\n\nThe most important reading is the Gospel, which tells us the words and actions of Jesus. We stand up to show how special it is, and we listen with all our hearts.\n\nThen the priest talks to us about what the readings mean and how we can live them at home and at school. This is called the homily.\n\nGod is speaking to you at Mass. All you have to do is listen.\n\n**Little prayer:** *Speak, Lord, for I am listening.*"},
            {"title": "5. The Great Thanksgiving", "body_md": "Now comes the most holy part of the Mass. The priest stands at the altar with bread and wine.\n\nHe says the very words Jesus said at the Last Supper: *\"This is my Body... This is my Blood.\"* And something wonderful happens that we cannot see with our eyes: the bread and wine truly become the Body and Blood of Jesus.\n\nThis is a great mystery and a great gift. Jesus gives Himself to us, just as He gave Himself on the cross.\n\nAt this moment we kneel very quietly, because Jesus is right there on the altar.\n\n**Little prayer:** *My Lord and my God, I believe that You are here.*"},
            {"title": "6. Jesus Comes to Us", "body_md": "Before Communion, we all pray together the prayer Jesus taught us: the *Our Father*. Then we share a sign of peace with the people around us.\n\nNow the people who are ready go up to receive Holy Communion — the Body of Jesus. When you are old enough and have made your First Communion, you will receive Him too.\n\nUntil then, you can go up for a blessing, and you can make a little prayer in your heart, asking Jesus to come to you spiritually.\n\nReceiving Jesus is the greatest gift of the Mass. He wants to be close to you.\n\n**Little prayer:** *Jesus, come into my heart and stay with me.*"},
            {"title": "7. Go in Peace", "body_md": "The Mass is almost over. The priest blesses us once more with the Sign of the Cross, and then he says, *\"Go in peace.\"*\n\nBut this is not just a goodbye. It is a mission! Jesus has filled us with His love, and now He sends us out to share that love with everyone we meet.\n\nWe can be kind to our family, gentle with our friends, and helpful to those in need. In this way, we bring a little bit of the Mass out into the whole week.\n\nWe answer joyfully, *\"Thanks be to God!\"*\n\n**Little prayer:** *Jesus, help me carry Your love to everyone today.*"},
            {"title": "8. Little Prayers to Know by Heart", "body_md": "Here are two beautiful prayers every child can learn by heart. Say them slowly, and let the words sink into your heart.\n\n**The Our Father:**\n\n*Our Father, who art in heaven, hallowed be Thy name; Thy kingdom come, Thy will be done, on earth as it is in heaven. Give us this day our daily bread, and forgive us our trespasses, as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen.*\n\n**The Hail Mary:**\n\n*Hail Mary, full of grace, the Lord is with thee. Blessed art thou amongst women, and blessed is the fruit of thy womb, Jesus. Holy Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.*"},
        ],
    },
]
