"""Novenas — nine-day devotional prayers.

Each novena ships with its AUTHENTIC traditional prayer (recited each day). A
short daily *contemplation* is generated by AI as the user progresses and is
cached permanently per (novena, day). Users pick their own start date; the
novena then runs nine consecutive days. Only one novena is active at a time,
but it can be restarted if abandoned.

All prayer + reflection text is localized into the user's language (EN/ES/IT)
through the shared, permanently-cached translator.
"""
from __future__ import annotations

import os
import uuid
from datetime import date, datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from motor.motor_asyncio import AsyncIOMotorDatabase

from lang_ctx import get_lang

MODEL = "claude-sonnet-4-5-20250929"

# --------------------------------------------------------------------------- #
# Catalog — authentic novena prayers.                                          #
# `day_intentions` is provided where the traditional novena has distinct daily #
# parts (Divine Mercy souls, St Michael's nine choirs); otherwise the main     #
# prayer is recited each day and the AI contemplation gives daily variety.     #
# --------------------------------------------------------------------------- #
NOVENAS: List[Dict[str, Any]] = [
    {
        "slug": "st-therese-little-flower",
        "name": "St. Thérèse the Little Flower Novena",
        "patron": "St. Thérèse of Lisieux",
        "feast": "October 1",
        "theme": "Trust, little ways, and a shower of roses",
        "color": "#D47B95", "icon": "rose-outline",
        "intro": "St. Thérèse promised to spend her heaven doing good upon earth and to let fall a shower of roses. This novena entrusts your intentions to her 'little way' of confidence and love.",
        "main_prayer": "O Little Thérèse of the Child Jesus, please pick for me a rose from the heavenly gardens and send it to me as a message of love. O Little Flower of Jesus, ask God today to grant the favors I now place with confidence in your hands… (mention your intention). St. Thérèse, help me to always believe, as you did, in God's great love for me, so that I might imitate your 'Little Way' each day. Amen.",
    },
    {
        "slug": "divine-mercy",
        "name": "Divine Mercy Novena",
        "patron": "The Divine Mercy of Jesus",
        "feast": "Divine Mercy Sunday (Sunday after Easter)",
        "theme": "Bringing all souls to the ocean of God's mercy",
        "color": "#3B6FB0", "icon": "water-outline",
        "intro": "Given by Jesus to St. Faustina, this novena brings a different group of souls each day to the fountain of Divine Mercy, ideally prayed with the Chaplet of Divine Mercy.",
        "main_prayer": "Most Merciful Jesus, whose very nature is compassion, receive into the abode of Your Most Compassionate Heart the souls I bring before You today. By Your tender mercy, draw them into the ocean of Your Mercy. I trust in You. (Pray the Chaplet of Divine Mercy.)",
        "day_intentions": [
            "Today bring to Me all mankind, especially all sinners.",
            "Today bring to Me the souls of priests and religious.",
            "Today bring to Me all devout and faithful souls.",
            "Today bring to Me those who do not yet believe in God and those who do not yet know Me.",
            "Today bring to Me the souls of those who have separated themselves from My Church.",
            "Today bring to Me the meek and humble souls and the souls of little children.",
            "Today bring to Me the souls who especially venerate and glorify My Mercy.",
            "Today bring to Me the souls who are in the prison of Purgatory.",
            "Today bring to Me souls who have become lukewarm.",
        ],
    },
    {
        "slug": "sacred-heart-jesus",
        "name": "Sacred Heart of Jesus Novena",
        "patron": "The Sacred Heart of Jesus",
        "feast": "Friday after Corpus Christi",
        "theme": "Confidence in the Heart that loves us",
        "color": "#9E1B1B", "icon": "heart-outline",
        "intro": "A novena of loving trust in the Heart of Jesus, source of all blessings, who promised that those who honor His Heart would never be confounded.",
        "main_prayer": "O most holy Heart of Jesus, fountain of every blessing, I adore You, I love You, and with lively sorrow for my sins I offer You this poor heart of mine. Make me humble, patient, pure, and wholly obedient to Your will. Grant, good Jesus, that I may live in You and for You. Protect me in the midst of danger; comfort me in my afflictions; and grant me the grace I now ask of You… (mention your intention). Sacred Heart of Jesus, I place all my trust in You. Amen.",
    },
    {
        "slug": "st-joseph",
        "name": "St. Joseph Novena",
        "patron": "St. Joseph",
        "feast": "March 19",
        "theme": "The powerful intercession of the foster-father of Jesus",
        "color": "#5B7C99", "icon": "construct-outline",
        "intro": "St. Joseph, guardian of the Holy Family and patron of the universal Church, is a sure and powerful intercessor. Entrust your needs to his fatherly care.",
        "main_prayer": "O glorious St. Joseph, faithful follower of Jesus Christ, to you I raise my heart and hands to implore your powerful intercession. Obtain for me from the kind Heart of Jesus the help and graces necessary for my spiritual and temporal welfare, and the particular favor I now ask… (mention your intention). Guardian of the Word Incarnate, I feel confident that your prayers on my behalf will be graciously heard before the throne of God. Amen.",
    },
    {
        "slug": "our-lady-perpetual-help",
        "name": "Our Lady of Perpetual Help Novena",
        "patron": "Our Lady of Perpetual Help",
        "feast": "June 27",
        "theme": "The Mother who never fails to help",
        "color": "#5B3475", "icon": "flower-outline",
        "intro": "Before her ancient icon, countless faithful have found a Mother ever ready to help. Bring her your every necessity with childlike confidence.",
        "main_prayer": "O Mother of Perpetual Help, grant that I may ever invoke your most powerful name, which is the safeguard of the living and the salvation of the dying. O purest Mary, let your name henceforth be ever on my lips. Delay not, O Blessed Lady, to help me whenever I call on you, for in all my needs, in all my temptations, I shall never cease to call on you, ever repeating your sacred name, Mary. Obtain for me the grace I now ask… (mention your intention). Amen.",
    },
    {
        "slug": "st-jude",
        "name": "St. Jude Novena",
        "patron": "St. Jude Thaddeus",
        "feast": "October 28",
        "theme": "Hope in desperate and impossible cases",
        "color": "#2A5A3B", "icon": "shield-checkmark-outline",
        "intro": "St. Jude, the apostle invoked in the most hopeless cases, is a faithful friend in trouble. Turn to him with confidence when all else seems lost.",
        "main_prayer": "Most holy Apostle, St. Jude, faithful servant and friend of Jesus, the Church honors and invokes you universally as the patron of hopeless cases, of things almost despaired of. Pray for me, who am so miserable; make use, I implore you, of that particular privilege given to you to bring visible and speedy help where help is almost despaired of. Come to my assistance in this great need, that I may receive the consolation and help of heaven in all my necessities, especially… (mention your intention), and that I may praise God with you always. Amen.",
    },
    {
        "slug": "st-michael-archangel",
        "name": "St. Michael the Archangel Novena",
        "patron": "St. Michael the Archangel",
        "feast": "September 29",
        "theme": "Protection through the nine choirs of angels",
        "color": "#B45309", "icon": "flash-outline",
        "intro": "Based on the Chaplet of St. Michael, each day honors one of the nine choirs of angels, imploring their protection and intercession.",
        "main_prayer": "St. Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil. May God rebuke him, we humbly pray; and do thou, O Prince of the heavenly host, by the power of God, cast into hell Satan and all the evil spirits who prowl about the world seeking the ruin of souls. Amen. (Glorious St. Michael, obtain for me the favor I now ask…)",
        "day_intentions": [
            "By the intercession of the Seraphim, may the Lord make us worthy to burn with the fire of perfect charity.",
            "By the intercession of the Cherubim, may the Lord grant us grace to leave the ways of sin and run in the paths of Christian perfection.",
            "By the intercession of the Thrones, may the Lord infuse into our hearts a true and sincere spirit of humility.",
            "By the intercession of the Dominions, may the Lord give us grace to govern our senses and overcome our unruly passions.",
            "By the intercession of the Powers, may the Lord protect our souls against the snares and temptations of the devil.",
            "By the intercession of the Virtues, may the Lord preserve us from evil and keep us from falling into temptation.",
            "By the intercession of the Principalities, may God fill our souls with a true spirit of obedience.",
            "By the intercession of the Archangels, may the Lord give us perseverance in faith and in all good works.",
            "By the intercession of all the Angels, may the Lord grant us their guardianship in this mortal life and conduct us hereafter to eternal glory.",
        ],
    },
    {
        "slug": "our-lady-lourdes",
        "name": "Our Lady of Lourdes Novena",
        "patron": "Our Lady of Lourdes",
        "feast": "February 11",
        "theme": "Healing and trust at the grotto",
        "color": "#4F9DDE", "icon": "water-outline",
        "intro": "At Lourdes the Immaculate Conception appeared to St. Bernadette and a spring of healing flowed. Bring your needs of body and soul to the Immaculate Mother.",
        "main_prayer": "O ever Immaculate Virgin, Mother of Mercy, Health of the sick, Refuge of sinners, Comfort of the afflicted, you know my wants, my troubles, my sufferings. Deign to cast upon me a look of mercy. By appearing in the grotto of Lourdes you were pleased to make it a privileged sanctuary from which you dispense your favors; already many sufferers have obtained the cure of their infirmities. I come, therefore, with confidence to implore your maternal intercession. Obtain, O loving Mother, the grant of my requests… (mention your intention). Through gratitude for your favors, I will endeavor to imitate your virtues, that I may one day share your glory. Amen.",
    },
    {
        "slug": "st-anthony-padua",
        "name": "St. Anthony of Padua Novena",
        "patron": "St. Anthony of Padua",
        "feast": "June 13",
        "theme": "Finder of what is lost; herald of the Gospel",
        "color": "#8B5E3C", "icon": "book-outline",
        "intro": "St. Anthony, wonder-worker and finder of what is lost, draws hearts back to Christ. Confidently entrust to him your intentions, great and small.",
        "main_prayer": "O holy St. Anthony, gentlest of saints, your love for God and charity for His creatures made you worthy, while on earth, to possess miraculous powers. Miracles waited on your word, which you were always ready to ask for those in trouble or anxiety. Encouraged by this thought, I implore you to obtain for me the favor I seek… (mention your intention). The answer to my prayer may require a miracle; even so, you are the saint of miracles. O gentle and loving St. Anthony, whose heart was ever full of human sympathy, whisper my petition into the ears of the sweet Infant Jesus, and the gratitude of my heart will ever be yours. Amen.",
    },
    {
        "slug": "guardian-angel",
        "name": "Guardian Angel Novena",
        "patron": "Your Guardian Angel",
        "feast": "October 2",
        "theme": "The faithful companion God gave to guide you",
        "color": "#C5A059", "icon": "sparkles-outline",
        "intro": "God has given you an angel to light and guard, to rule and guide you. This novena thanks and invokes your faithful heavenly companion.",
        "main_prayer": "Angel of God, my guardian dear, to whom God's love commits me here, ever this day be at my side, to light and guard, to rule and guide. Amen.\n\nO holy Angel, attend to my prayers and present them before the throne of God. Help me to know God's will and to do it faithfully, defend me from all dangers of soul and body, and lead me safely home to heaven. Obtain for me the grace I now ask… (mention your intention). Amen.",
    },
    {
        "slug": "st-lucy",
        "name": "St. Lucy Novena",
        "patron": "St. Lucy of Syracuse",
        "feast": "December 13",
        "theme": "Light, purity, and the sight of faith",
        "color": "#C99A2E", "icon": "eye-outline",
        "intro": "St. Lucy, whose name means 'light', is invoked for the eyes and for the inner light of faith. A virgin and martyr, she witnessed to Christ even unto death.",
        "main_prayer": "O glorious St. Lucy, who chose to lose your eyes and even life itself rather than betray your faith and stain your soul, obtain for us the grace to use our bodily eyes for the spiritual benefit of our souls, and when the light of this passing world is over, may we enjoy the eternal Light, Jesus your Spouse. By your intercession obtain for me the favor I now ask… (mention your intention). St. Lucy, virgin and martyr, hear my prayers and obtain my petitions. Amen.",
    },
]

NOVENA_BY_SLUG = {n["slug"]: n for n in NOVENAS}


def _public_catalog(n: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "slug": n["slug"], "name": n["name"], "patron": n["patron"],
        "feast": n["feast"], "theme": n["theme"], "color": n["color"], "icon": n["icon"],
        "intro": n["intro"], "days": 9,
    }


def _public_detail(n: Dict[str, Any]) -> Dict[str, Any]:
    out = _public_catalog(n)
    out["main_prayer"] = n["main_prayer"]
    out["day_intentions"] = n.get("day_intentions")  # may be None
    return out


def _parse_date(v: str) -> date:
    return datetime.strptime(v, "%Y-%m-%d").date()


def _enrollment_public(e: Dict[str, Any]) -> Dict[str, Any]:
    start = e["start_date"]
    end = (_parse_date(start) + timedelta(days=8)).isoformat()
    completed = sorted(set(e.get("completed_days", [])))
    return {
        "slug": e["slug"], "start_date": start, "end_date": end,
        "completed_days": completed, "status": e.get("status", "active"),
        "total_days": 9,
    }


async def _localize_strings(db, values: List[str]) -> List[str]:
    lang = get_lang()
    if lang == "en" or not values:
        return values
    try:
        from i18n_translate import translate_texts
        return await translate_texts(db, os.environ.get("EMERGENT_LLM_KEY", ""), values, lang)
    except Exception:  # noqa: BLE001
        return values


async def _reflection(db, emergent_llm_key: str, n: Dict[str, Any], day: int) -> str:
    """Return (and cache) the AI daily contemplation for a novena day, in English."""
    col = db["novena_reflections"]
    doc = await col.find_one({"slug": n["slug"], "day": day}, {"_id": 0, "text": 1})
    if doc and (doc.get("text") or "").strip():
        return doc["text"].strip()
    intention = ""
    if n.get("day_intentions") and 1 <= day <= len(n["day_intentions"]):
        intention = f" Today's traditional intention: {n['day_intentions'][day - 1]}"
    system = (
        "You are a faithful Catholic spiritual director writing a brief daily contemplation for a novena. "
        "Write 2-3 warm, reverent sentences (max ~55 words) that the person can carry through the day. "
        "Stay orthodox and Scripture-rooted; no headings, no markdown, plain prose."
    )
    user = (
        f"Novena: {n['name']} (to {n['patron']}). Theme: {n['theme']}. "
        f"This is Day {day} of 9.{intention} "
        "Give a short contemplation tying today to the novena's theme and to growth in trust and love of God."
    )
    text = ""
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
        chat = LlmChat(api_key=emergent_llm_key, session_id=f"nov-{n['slug']}-{day}", system_message=system).with_model("anthropic", MODEL)
        resp = await chat.send_message(UserMessage(text=user))
        text = (resp if isinstance(resp, str) else str(resp)).strip()
    except Exception:  # noqa: BLE001
        text = ""
    if text:
        await col.update_one({"slug": n["slug"], "day": day}, {"$set": {"slug": n["slug"], "day": day, "text": text}}, upsert=True)
    return text


class StartModel(BaseModel):
    start_date: str  # YYYY-MM-DD


class DayModel(BaseModel):
    day: int


def build_router(db: AsyncIOMotorDatabase, get_current_user, emergent_llm_key: str = "") -> APIRouter:
    router = APIRouter(prefix="/novenas", tags=["novenas"])
    enroll = db["novena_enrollments"]

    async def _active(user_id: str) -> Optional[Dict[str, Any]]:
        return await enroll.find_one({"user_id": user_id, "status": "active"}, {"_id": 0})

    @router.get("")
    async def list_novenas(user=Depends(get_current_user)):
        items = [_public_catalog(n) for n in NOVENAS]
        names = await _localize_strings(db, [i["name"] for i in items])
        themes = await _localize_strings(db, [i["theme"] for i in items])
        for it, nm, th in zip(items, names, themes):
            it["name"], it["theme"] = nm, th
        active = await _active(user.user_id)
        return {"items": items, "active": _enrollment_public(active) if active else None}

    @router.get("/active")
    async def get_active(user=Depends(get_current_user)):
        a = await _active(user.user_id)
        if not a:
            return {"active": None}
        out = _enrollment_public(a)
        out["novena"] = _public_catalog(NOVENA_BY_SLUG[a["slug"]])
        return {"active": out}

    @router.post("/{slug}/start")
    async def start(slug: str, payload: StartModel, user=Depends(get_current_user)):
        n = NOVENA_BY_SLUG.get(slug)
        if not n:
            raise HTTPException(status_code=404, detail="Novena not found")
        try:
            _parse_date(payload.start_date)
        except ValueError:
            raise HTTPException(status_code=400, detail="start_date must be YYYY-MM-DD")
        existing = await _active(user.user_id)
        if existing and existing["slug"] != slug:
            raise HTTPException(
                status_code=409,
                detail={"message": "You already have an active novena.", "active_slug": existing["slug"]},
            )
        # (Re)start: replace any prior enrollment for this user+slug.
        await enroll.delete_many({"user_id": user.user_id, "slug": slug})
        doc = {
            "user_id": user.user_id, "slug": slug, "start_date": payload.start_date,
            "completed_days": [], "status": "active",
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        await enroll.insert_one(dict(doc))
        return _enrollment_public(doc)

    @router.post("/stop")
    async def stop(user=Depends(get_current_user)):
        await enroll.update_many({"user_id": user.user_id, "status": "active"}, {"$set": {"status": "abandoned"}})
        return {"ok": True}

    @router.post("/{slug}/complete-day")
    async def complete_day(slug: str, payload: DayModel, user=Depends(get_current_user)):
        if payload.day < 1 or payload.day > 9:
            raise HTTPException(status_code=400, detail="day must be 1-9")
        e = await enroll.find_one({"user_id": user.user_id, "slug": slug, "status": "active"})
        if not e:
            raise HTTPException(status_code=404, detail="No active enrollment for this novena")
        done = sorted(set(e.get("completed_days", [])) | {payload.day})
        status = "completed" if len(done) >= 9 else "active"
        await enroll.update_one({"_id": e["_id"]}, {"$set": {"completed_days": done, "status": status}})
        e["completed_days"], e["status"] = done, status
        return _enrollment_public(e)

    @router.get("/{slug}")
    async def get_one(slug: str, user=Depends(get_current_user)):
        n = NOVENA_BY_SLUG.get(slug)
        if not n:
            raise HTTPException(status_code=404, detail="Novena not found")
        out = _public_detail(n)
        # Localize name/theme/intro/main_prayer/day_intentions
        base = [out["name"], out["theme"], out["intro"], out["main_prayer"]]
        di = out.get("day_intentions") or []
        tr = await _localize_strings(db, base + list(di))
        out["name"], out["theme"], out["intro"], out["main_prayer"] = tr[0], tr[1], tr[2], tr[3]
        if di:
            out["day_intentions"] = tr[4:4 + len(di)]
        e = await enroll.find_one({"user_id": user.user_id, "slug": slug, "status": {"$in": ["active", "completed"]}}, {"_id": 0})
        out["enrollment"] = _enrollment_public(e) if e else None
        return out

    @router.get("/{slug}/reflection/{day}")
    async def reflection(slug: str, day: int, user=Depends(get_current_user)):
        n = NOVENA_BY_SLUG.get(slug)
        if not n:
            raise HTTPException(status_code=404, detail="Novena not found")
        if day < 1 or day > 9:
            raise HTTPException(status_code=400, detail="day must be 1-9")
        text_en = await _reflection(db, emergent_llm_key, n, day)
        [text] = await _localize_strings(db, [text_en]) if text_en else [""]
        return {"slug": slug, "day": day, "reflection": text}

    return router
