"""One-off seeder: fill the "Saint of the Day" library with a full draft
entry for every calendar day of the year (Jan 1 – Dec 31, 365 days).

- Each entry is generated by Claude using the SAME prompt/schema as the
  admin "Propose" endpoint in saints.py, so the information sheet (name,
  rank, verified quote + source, biography, recommended action, public-domain
  picture) is fully filled out.
- Everything is inserted with status="draft" so an admin reviews/approves.
- Dates that already have an approved OR draft PRIMARY entry are SKIPPED
  (idempotent: safe to re-run; it only fills the gaps).

Run in the background:
    cd /app/backend && python -m scripts.seed_saints_drafts > /tmp/seed_saints.log 2>&1 &
Monitor:
    tail -f /tmp/seed_saints.log
"""
from __future__ import annotations

import asyncio
import os
import sys
import uuid
from datetime import date as _date

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient

# Import the exact generation primitives the admin endpoint uses.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"))

from saints import (  # noqa: E402
    SYSTEM_PROMPT,
    ProposeRequest,
    SaintModel,
    _build_user_block,
    _extract_json,
    _now,
)

EMERGENT_LLM_KEY = os.environ.get("EMERGENT_LLM_KEY", "")
MODEL = "claude-sonnet-4-5-20250929"
CONCURRENCY = 5          # parallel Claude calls
MAX_RETRIES = 2          # per date


def all_year_dates() -> list[str]:
    """Every MM-DD from 01-01 to 12-31 (uses 2025, a non-leap year → 365)."""
    out: list[str] = []
    d = _date(2025, 1, 1)
    end = _date(2025, 12, 31)
    while d <= end:
        out.append(d.strftime("%Y-%m-%d"))
        d = _date.fromordinal(d.toordinal() + 1)
    return out


async def generate_one(db, llm, yyyymmdd: str) -> str:
    """Generate + insert a single draft for the given date. Returns a status str."""
    from emergentintegrations.llm.chat import LlmChat, UserMessage

    mmdd = yyyymmdd[5:]
    # Avoid repeating names already present for this MM-DD.
    existing_names: list[str] = []
    async for d in db.saints.find({"feast_date": mmdd}, {"_id": 0, "name": 1}):
        nm = (d.get("name") or "").strip()
        if nm:
            existing_names.append(nm)

    req = ProposeRequest(date=yyyymmdd, is_primary=True)
    user_block = _build_user_block(req, exclude_names=existing_names)

    last_err = ""
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            chat = LlmChat(
                api_key=EMERGENT_LLM_KEY,
                session_id=f"saints-seed-{uuid.uuid4().hex[:12]}",
                system_message=SYSTEM_PROMPT,
            ).with_model("anthropic", MODEL)
            response = await chat.send_message(UserMessage(text=user_block))
            data = _extract_json(response or "")
            doc = SaintModel(
                saint_id=f"st_{uuid.uuid4().hex[:14]}",
                name=str(data.get("name") or "").strip(),
                rank=str(data.get("rank") or "saint").strip().lower(),
                feast_date=(data.get("feast_date") or mmdd),
                is_primary=True,
                picture_url=(data.get("picture_url") or None),
                picture_source=(data.get("picture_source") or None),
                quote=str(data.get("quote") or "").strip(),
                quote_source=str(data.get("quote_source") or "").strip(),
                biography=str(data.get("biography") or "").strip(),
                recommended_action=str(data.get("recommended_action") or "").strip(),
                status="draft",
                proposed_by_ai=True,
                proposed_at=_now(),
            )
            if not doc.name or not doc.biography or not doc.recommended_action:
                raise ValueError("incomplete entry (missing name/bio/action)")
            await db.saints.insert_one(doc.model_dump())
            return f"OK   {mmdd}  {doc.name} [{doc.rank}]"
        except Exception as e:  # noqa: BLE001
            last_err = str(e)
            await asyncio.sleep(1.5 * attempt)
    return f"FAIL {mmdd}  ({last_err[:120]})"


async def main() -> None:
    if not EMERGENT_LLM_KEY:
        print("ERROR: EMERGENT_LLM_KEY not set", flush=True)
        return
    client = AsyncIOMotorClient(os.environ["MONGO_URL"])
    db = client[os.environ["DB_NAME"]]

    # Dates that already have an approved or draft PRIMARY entry → skip.
    taken: set[str] = set()
    async for d in db.saints.find(
        {"status": {"$in": ["approved", "draft"]}, "is_primary": True},
        {"_id": 0, "feast_date": 1},
    ):
        fd = d.get("feast_date")
        if fd:
            taken.add(fd)

    targets = [d for d in all_year_dates() if d[5:] not in taken]
    print(f"Year days: 365 | already filled: {len(taken)} | to generate: {len(targets)}", flush=True)

    sem = asyncio.Semaphore(CONCURRENCY)
    done = {"n": 0, "ok": 0, "fail": 0}

    async def worker(yyyymmdd: str):
        async with sem:
            res = await generate_one(db, None, yyyymmdd)
            done["n"] += 1
            if res.startswith("OK"):
                done["ok"] += 1
            else:
                done["fail"] += 1
            print(f"[{done['n']}/{len(targets)}] {res}", flush=True)

    # Reuse a single LlmChat import path; chat objects are created per call.
    await asyncio.gather(*(worker(d) for d in targets))

    drafts = await db.saints.count_documents({"status": "draft"})
    print(
        f"DONE. generated_ok={done['ok']} failed={done['fail']} "
        f"total_drafts_now={drafts}",
        flush=True,
    )
    client.close()


if __name__ == "__main__":
    asyncio.run(main())
